
  name: probaflask
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: will be # 79 char long summary
  description: |
    

  grade: stable
  confinement: devmode # use 'strict' once you have the right plugs and slots
 apps:
  probaflask:
    command: run
parts:
    probaflask:
      source: https://github.com/kocicjelena/probaflask.git
      plugin: python
  
