
  name: probaflask
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Single-line elevator pitch for your amazing snap # 79 char long summary
  description: |
    This is my-snap's description. You have a paragraph or two to tell the
    most important story about your snap. Keep it under 100 words though,
    we live in tweetspace and your description wants to look good in the snap
    store.

  grade: stable
  confinement: devmode # use 'strict' once you have the right plugs and slots
 apps:
  statusnap:
    command: bin/probaflask
    plugin: python
parts:
    gnu-hello:
      source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
      plugin: autotools
    gnu-bash:
      source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
      plugin: autotools
      configflags: ["--infodir=/var/bash/info"]
    probaflask:
      source: https://github.com/kocicjelena/probaflask.git
      source-tag: v1.1.3
      plugin: python
  
